[package]
name = "zorq-raft"
version = "0.1.0"
authors = ["Marc Göldner <zorq@posteo.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
